/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */
export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];
export declare const OrderStatus: {
    readonly pending: "pending";
    readonly preparing: "preparing";
    readonly completed: "completed";
};
//# sourceMappingURL=orderStatus.d.ts.map