/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */

export interface MenuItem {
  id: number;
  categoryId: number;
  /** @nullable */
  categoryName?: string | null;
  name: string;
  /** @nullable */
  description?: string | null;
  price: number;
  /** @nullable */
  imageUrl?: string | null;
  available: boolean;
  createdAt: string;
}
