/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all categories
 */
export declare const ListCategoriesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    createdAt: string;
}, {
    id: number;
    name: string;
    createdAt: string;
}>;
export declare const ListCategoriesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    createdAt: string;
}, {
    id: number;
    name: string;
    createdAt: string;
}>, "many">;
/**
 * @summary Create a category
 */
export declare const CreateCategoryBody: zod.ZodObject<{
    name: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
}, {
    name: string;
}>;
/**
 * @summary List all menu items
 */
export declare const ListMenuItemsQueryParams: zod.ZodObject<{
    categoryId: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    categoryId?: number | undefined;
}, {
    categoryId?: number | undefined;
}>;
export declare const ListMenuItemsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    categoryId: zod.ZodNumber;
    categoryName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    available: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    createdAt: string;
    categoryId: number;
    price: number;
    available: boolean;
    categoryName?: string | null | undefined;
    description?: string | null | undefined;
    imageUrl?: string | null | undefined;
}, {
    id: number;
    name: string;
    createdAt: string;
    categoryId: number;
    price: number;
    available: boolean;
    categoryName?: string | null | undefined;
    description?: string | null | undefined;
    imageUrl?: string | null | undefined;
}>;
export declare const ListMenuItemsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    categoryId: zod.ZodNumber;
    categoryName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    available: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    createdAt: string;
    categoryId: number;
    price: number;
    available: boolean;
    categoryName?: string | null | undefined;
    description?: string | null | undefined;
    imageUrl?: string | null | undefined;
}, {
    id: number;
    name: string;
    createdAt: string;
    categoryId: number;
    price: number;
    available: boolean;
    categoryName?: string | null | undefined;
    description?: string | null | undefined;
    imageUrl?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a menu item
 */
export declare const createMenuItemBodyPriceMin = 0;
export declare const CreateMenuItemBody: zod.ZodObject<{
    categoryId: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodNumber;
    imageUrl: zod.ZodOptional<zod.ZodString>;
    available: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    categoryId: number;
    price: number;
    description?: string | undefined;
    imageUrl?: string | undefined;
    available?: boolean | undefined;
}, {
    name: string;
    categoryId: number;
    price: number;
    description?: string | undefined;
    imageUrl?: string | undefined;
    available?: boolean | undefined;
}>;
/**
 * @summary Update a menu item
 */
export declare const UpdateMenuItemParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const updateMenuItemBodyPriceMin = 0;
export declare const UpdateMenuItemBody: zod.ZodObject<{
    categoryId: zod.ZodOptional<zod.ZodNumber>;
    name: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodOptional<zod.ZodNumber>;
    imageUrl: zod.ZodOptional<zod.ZodString>;
    available: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    categoryId?: number | undefined;
    description?: string | undefined;
    price?: number | undefined;
    imageUrl?: string | undefined;
    available?: boolean | undefined;
}, {
    name?: string | undefined;
    categoryId?: number | undefined;
    description?: string | undefined;
    price?: number | undefined;
    imageUrl?: string | undefined;
    available?: boolean | undefined;
}>;
export declare const UpdateMenuItemResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    categoryId: zod.ZodNumber;
    categoryName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    available: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    createdAt: string;
    categoryId: number;
    price: number;
    available: boolean;
    categoryName?: string | null | undefined;
    description?: string | null | undefined;
    imageUrl?: string | null | undefined;
}, {
    id: number;
    name: string;
    createdAt: string;
    categoryId: number;
    price: number;
    available: boolean;
    categoryName?: string | null | undefined;
    description?: string | null | undefined;
    imageUrl?: string | null | undefined;
}>;
/**
 * @summary Delete a menu item
 */
export declare const DeleteMenuItemParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List all orders
 */
export declare const ListOrdersQueryParams: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodEnum<["pending", "preparing", "completed"]>>;
}, "strip", zod.ZodTypeAny, {
    status?: "pending" | "preparing" | "completed" | undefined;
}, {
    status?: "pending" | "preparing" | "completed" | undefined;
}>;
export declare const ListOrdersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    tableNumber: zod.ZodNumber;
    status: zod.ZodEnum<["pending", "preparing", "completed"]>;
    totalPrice: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        menuItemId: zod.ZodNumber;
        menuItemName: zod.ZodString;
        quantity: zod.ZodNumber;
        unitPrice: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }, {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "preparing" | "completed";
    id: number;
    createdAt: string;
    tableNumber: number;
    totalPrice: number;
    items: {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }[];
    notes?: string | null | undefined;
}, {
    status: "pending" | "preparing" | "completed";
    id: number;
    createdAt: string;
    tableNumber: number;
    totalPrice: number;
    items: {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }[];
    notes?: string | null | undefined;
}>;
export declare const ListOrdersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    tableNumber: zod.ZodNumber;
    status: zod.ZodEnum<["pending", "preparing", "completed"]>;
    totalPrice: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        menuItemId: zod.ZodNumber;
        menuItemName: zod.ZodString;
        quantity: zod.ZodNumber;
        unitPrice: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }, {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "preparing" | "completed";
    id: number;
    createdAt: string;
    tableNumber: number;
    totalPrice: number;
    items: {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }[];
    notes?: string | null | undefined;
}, {
    status: "pending" | "preparing" | "completed";
    id: number;
    createdAt: string;
    tableNumber: number;
    totalPrice: number;
    items: {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }[];
    notes?: string | null | undefined;
}>, "many">;
/**
 * @summary Create an order
 */
export declare const CreateOrderBody: zod.ZodObject<{
    tableNumber: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodString>;
    items: zod.ZodArray<zod.ZodObject<{
        menuItemId: zod.ZodNumber;
        quantity: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        menuItemId: number;
        quantity: number;
    }, {
        menuItemId: number;
        quantity: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    tableNumber: number;
    items: {
        menuItemId: number;
        quantity: number;
    }[];
    notes?: string | undefined;
}, {
    tableNumber: number;
    items: {
        menuItemId: number;
        quantity: number;
    }[];
    notes?: string | undefined;
}>;
/**
 * @summary Get order statistics for the kitchen dashboard
 */
export declare const GetOrderStatsResponse: zod.ZodObject<{
    pending: zod.ZodNumber;
    preparing: zod.ZodNumber;
    completed: zod.ZodNumber;
    totalToday: zod.ZodNumber;
    revenueToday: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    pending: number;
    preparing: number;
    completed: number;
    totalToday: number;
    revenueToday: number;
}, {
    pending: number;
    preparing: number;
    completed: number;
    totalToday: number;
    revenueToday: number;
}>;
/**
 * @summary Advance order status to next stage
 */
export declare const AdvanceOrderStatusParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const AdvanceOrderStatusBody: zod.ZodObject<{
    status: zod.ZodEnum<["pending", "preparing", "completed"]>;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "preparing" | "completed";
}, {
    status: "pending" | "preparing" | "completed";
}>;
export declare const AdvanceOrderStatusResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    tableNumber: zod.ZodNumber;
    status: zod.ZodEnum<["pending", "preparing", "completed"]>;
    totalPrice: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        menuItemId: zod.ZodNumber;
        menuItemName: zod.ZodString;
        quantity: zod.ZodNumber;
        unitPrice: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }, {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "preparing" | "completed";
    id: number;
    createdAt: string;
    tableNumber: number;
    totalPrice: number;
    items: {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }[];
    notes?: string | null | undefined;
}, {
    status: "pending" | "preparing" | "completed";
    id: number;
    createdAt: string;
    tableNumber: number;
    totalPrice: number;
    items: {
        id: number;
        menuItemId: number;
        menuItemName: string;
        quantity: number;
        unitPrice: number;
    }[];
    notes?: string | null | undefined;
}>;
//# sourceMappingURL=api.d.ts.map