/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */
export type OrderStatusPatchStatus = typeof OrderStatusPatchStatus[keyof typeof OrderStatusPatchStatus];
export declare const OrderStatusPatchStatus: {
    readonly pending: "pending";
    readonly preparing: "preparing";
    readonly completed: "completed";
};
//# sourceMappingURL=orderStatusPatchStatus.d.ts.map