/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */

export interface OrderStats {
  pending: number;
  preparing: number;
  completed: number;
  totalToday: number;
  revenueToday: number;
}
