/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all categories
 */
export const ListCategoriesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "createdAt": zod.string()
})
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem)


/**
 * @summary Create a category
 */



export const CreateCategoryBody = zod.object({
  "name": zod.string().min(1)
})


/**
 * @summary List all menu items
 */
export const ListMenuItemsQueryParams = zod.object({
  "categoryId": zod.coerce.number().optional()
})

export const ListMenuItemsResponseItem = zod.object({
  "id": zod.number(),
  "categoryId": zod.number(),
  "categoryName": zod.string().nullish(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "imageUrl": zod.string().nullish(),
  "available": zod.boolean(),
  "createdAt": zod.string()
})
export const ListMenuItemsResponse = zod.array(ListMenuItemsResponseItem)


/**
 * @summary Create a menu item
 */

export const createMenuItemBodyPriceMin = 0;



export const CreateMenuItemBody = zod.object({
  "categoryId": zod.number(),
  "name": zod.string().min(1),
  "description": zod.string().optional(),
  "price": zod.number().min(createMenuItemBodyPriceMin),
  "imageUrl": zod.string().optional(),
  "available": zod.boolean().optional()
})


/**
 * @summary Update a menu item
 */
export const UpdateMenuItemParams = zod.object({
  "id": zod.coerce.number()
})


export const updateMenuItemBodyPriceMin = 0;



export const UpdateMenuItemBody = zod.object({
  "categoryId": zod.number().optional(),
  "name": zod.string().min(1).optional(),
  "description": zod.string().optional(),
  "price": zod.number().min(updateMenuItemBodyPriceMin).optional(),
  "imageUrl": zod.string().optional(),
  "available": zod.boolean().optional()
})

export const UpdateMenuItemResponse = zod.object({
  "id": zod.number(),
  "categoryId": zod.number(),
  "categoryName": zod.string().nullish(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "imageUrl": zod.string().nullish(),
  "available": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a menu item
 */
export const DeleteMenuItemParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all orders
 */
export const ListOrdersQueryParams = zod.object({
  "status": zod.enum(['pending', 'preparing', 'completed']).optional()
})

export const ListOrdersResponseItem = zod.object({
  "id": zod.number(),
  "tableNumber": zod.number(),
  "status": zod.enum(['pending', 'preparing', 'completed']),
  "totalPrice": zod.number(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "menuItemId": zod.number(),
  "menuItemName": zod.string(),
  "quantity": zod.number(),
  "unitPrice": zod.number()
}))
})
export const ListOrdersResponse = zod.array(ListOrdersResponseItem)


/**
 * @summary Create an order
 */





export const CreateOrderBody = zod.object({
  "tableNumber": zod.number().min(1),
  "notes": zod.string().optional(),
  "items": zod.array(zod.object({
  "menuItemId": zod.number(),
  "quantity": zod.number().min(1)
})).min(1)
})


/**
 * @summary Get order statistics for the kitchen dashboard
 */
export const GetOrderStatsResponse = zod.object({
  "pending": zod.number(),
  "preparing": zod.number(),
  "completed": zod.number(),
  "totalToday": zod.number(),
  "revenueToday": zod.number()
})


/**
 * @summary Advance order status to next stage
 */
export const AdvanceOrderStatusParams = zod.object({
  "id": zod.coerce.number()
})

export const AdvanceOrderStatusBody = zod.object({
  "status": zod.enum(['pending', 'preparing', 'completed'])
})

export const AdvanceOrderStatusResponse = zod.object({
  "id": zod.number(),
  "tableNumber": zod.number(),
  "status": zod.enum(['pending', 'preparing', 'completed']),
  "totalPrice": zod.number(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "menuItemId": zod.number(),
  "menuItemName": zod.string(),
  "quantity": zod.number(),
  "unitPrice": zod.number()
}))
})


