/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */

export type OrderStatusPatchStatus = typeof OrderStatusPatchStatus[keyof typeof OrderStatusPatchStatus];


export const OrderStatusPatchStatus = {
  pending: 'pending',
  preparing: 'preparing',
  completed: 'completed',
} as const;
