/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Luka Food Restaurant API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Category {
  id: number;
  name: string;
  createdAt: string;
}

export interface CategoryInput {
  /** @minLength 1 */
  name: string;
}

export interface MenuItem {
  id: number;
  categoryId: number;
  /** @nullable */
  categoryName?: string | null;
  name: string;
  /** @nullable */
  description?: string | null;
  price: number;
  /** @nullable */
  imageUrl?: string | null;
  available: boolean;
  createdAt: string;
}

export interface MenuItemInput {
  categoryId: number;
  /** @minLength 1 */
  name: string;
  description?: string;
  /** @minimum 0 */
  price: number;
  imageUrl?: string;
  available?: boolean;
}

export interface MenuItemPatch {
  categoryId?: number;
  /** @minLength 1 */
  name?: string;
  description?: string;
  /** @minimum 0 */
  price?: number;
  imageUrl?: string;
  available?: boolean;
}

export interface OrderItem {
  id: number;
  menuItemId: number;
  menuItemName: string;
  quantity: number;
  unitPrice: number;
}

export interface OrderItemInput {
  menuItemId: number;
  /** @minimum 1 */
  quantity: number;
}

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export const OrderStatus = {
  pending: 'pending',
  preparing: 'preparing',
  completed: 'completed',
} as const;

export interface Order {
  id: number;
  tableNumber: number;
  status: OrderStatus;
  totalPrice: number;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
  items: OrderItem[];
}

export interface OrderInput {
  /** @minimum 1 */
  tableNumber: number;
  notes?: string;
  /** @minItems 1 */
  items: OrderItemInput[];
}

export type OrderStatusPatchStatus = typeof OrderStatusPatchStatus[keyof typeof OrderStatusPatchStatus];


export const OrderStatusPatchStatus = {
  pending: 'pending',
  preparing: 'preparing',
  completed: 'completed',
} as const;

export interface OrderStatusPatch {
  status: OrderStatusPatchStatus;
}

export interface OrderStats {
  pending: number;
  preparing: number;
  completed: number;
  totalToday: number;
  revenueToday: number;
}

export type ListMenuItemsParams = {
categoryId?: number;
};

export type ListOrdersParams = {
status?: ListOrdersStatus;
};

export type ListOrdersStatus = typeof ListOrdersStatus[keyof typeof ListOrdersStatus];


export const ListOrdersStatus = {
  pending: 'pending',
  preparing: 'preparing',
  completed: 'completed',
} as const;

